name: Checked Code

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: get npm version
        run: echo "NPM_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: get latest github release
        id: get-latest-version
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            return data.length === 0 ? '' : data[0].tag_name
      - name: config file version up check
        uses: actions/github-script@v6
        env:
          LATEST_VERSION: ${{ steps.get-latest-version.outputs.result }}
        with:
          script: |
            core.debug({
              current_version: process.env.LATEST_VERSION,
              latest_version: `"v${process.env.NPM_VERSION}"`
            })
            core.notice('package.jsonとCargo.tomlのバージョン更新をしたか確認してください')
            if (`"v${process.env.NPM_VERSION}"` === process.env.LATEST_VERSION) core.setFailed('リリース済みのバージョンです。')
